### ISSUE TITLE
Snippet in Head

### ISSUE THREAD

**Issue by bradyclifford** [SumoLogic/js-sumo-logger#113]
We are utilizing web components and would like them to use the same SumoLogic telemetry provider.  Do you offer instead of an npm package, a script snippet we can include in the HEAD of our html?

**Comment by desnor** [comment]
Not sure if this is still an issue for you @bradyclifford - but in the [README.md](https://github.com/SumoLogic/js-sumo-logger). they mention how you can do this by using the raw code from github, downloading it and then adding it into your `html` directly:

> From GitHub:
>
> Download or clone this repo.
> Copy the files in the src folder into your app/website source.
> Add `<script src="path/to/sumoLogger.js"></source>` to your pages or import or require the module in your app.
> Add a `<script>` block with the desired log call to your pages, or use the function as needed in your app, as explained in [Usage](https://github.com/SumoLogic/js-sumo-logger#user-content-usage).
