### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by alanevans** [SumoLogic/js-sumo-logger#118]
Hi - is it possible to estimate when a new release might be cut (so that latest features are available to install via NPM)?

The feature I'm most interested in is Carbon2 support https://github.com/SumoLogic/js-sumo-logger/pull/117 (required for sending metrics)

**Comment by bpolanczyk** [comment]
Hi! We're adjusting the release pipeline to a new flow. I'll try to release the new version this week.

**Comment by alanevans** [comment]
That is fantastic news! Thank you so much!

**Comment by bpolanczyk** [comment]
I've just released the updated version (2.8.0) and will draft a release on GH soon - enjoy!
