### ISSUE TITLE
Rename repo to `sumo-logger`

### ISSUE THREAD

**Issue by clementallen** [SumoLogic/js-sumo-logger#32]
It would probably be better if the repo name was the same as the published package on NPM if possible

**Comment by billsaysthis** [comment]
I checked internally, we could change it to something like `js-sumo-logger` or `sumo-js-logger` but `sumo-logger` is too generic.

**Comment by clementallen** [comment]
@billsaysthis if possible I think reaming to `js-sumo-logger` would be good

**Comment by billsaysthis** [comment]
Renamed to `js-sumo-logger`.
