### ISSUE TITLE
Question: Offline Mode

### ISSUE THREAD

**Issue by jbw91** [SumoLogic/js-sumo-logger#36]
I am building an Electron app, and want to log to SumoLogic using this SDK. As it is a desktop app, it will definitely be used offline, so I don't want to lose those logs, I want to batch them somewhere until the app is online again, and I can push those to SumoLogic.

Does this library provide any method out of the box to be able to handle being offline, and then pushing later when online? My thoughts are perhaps using `startLogSending` and `stopLogSending`, so when I go offline, I invoke the stop method, and then upon getting connection again, invoke the start method.

As a side note, are these batched logs persisted to a file? Or simply in memory?

**Comment by clementallen** [comment]
@jbw91 no offline functionality currently in this library.  My suggestion would be to cache the logs when offline in electron then send using this library once a connection is established.

`startLogSending` and `stopLogSending` only resume and pause sending logs in interval batches.  It may be possible to use them somehow to help with online-only sending but would require a bit of experimentation :)  If you wish to add in proper offline functionality that would be more than welcome!

Side note answer: Just persisted in memory for the time being as the intended behaviour is they are only cached for a short period so not much need to persist in a file.

cc @billsaysthis

**Comment by jbw91** [comment]
Awesome and quick answer! Thanks a ton!
