### ISSUE TITLE
Expose async interface from log method

### ISSUE THREAD

**Issue by c24w** [SumoLogic/js-sumo-logger#43]
Do you think it would be reasonable to expose something from the `log` method, so the caller could (optionally) wait for the result?  Our use case is when `interval === 0` (the default) where each call to `log` is associated with one HTTP request.  If `log` could essentially proxy and return the `axios` promise, this wouldn't be a breaking change.

It might be a bit more fiddly (and a less useful feature) to implement this when `interval > 0`, so perhaps it would only be enabled for the other case.

What do you think?

**Comment by clementallen** [comment]
@c24w if I was to write this library from scratch without having to consider breaking existing implementations, I would certainly do this.  I would remove the callback style `onSuccess` and `onError` methods passed when creating an instance and replace them with the log method returning a promise so it could be used like so:

```javascript
const logger = new SumoLogger(options);

logger.log(message)
  .then(response => {
    console.log(response);
  })
  .catch(error => {
    console.log(error);
  });

```

I haven't spent much time looking into whether this could be done without breaking existing usage but if it could be I would certainly support it.

**Comment by c24w** [comment]
Hi @clementallen!  In what way would this be a breaking change?  Currently nobody will be expecting a return value from `log`, so returning a promise shouldn't have adverse effects.  I appreciate that it would be trickier to implement for a logger which is batching-up multiple logs into a single HTTP request, but would it not at least be possible for a logger which isn't sending in batches?

**Comment by clementallen** [comment]
@c24w would it not throw an unhandled promise rejection warning if `log()` returned a rejected promise that wasn't handled by the user?

**Comment by c24w** [comment]
That's a very good point and definitely not something you want your logger doing!  :thinking:

Could the resultant promise be implemented to only ever resolve (never reject), passing something to indicate the status?  Pretty gross and hacky though.

Also, I suppose using callbacks or events wouldn't have that caveat.  Callbacks would change the signature though.  I can see why this isn't as trivial as I made it sound!

:man_shrugging:

Feel free to close the issue :)

**Comment by billsaysthis** [comment]
@clementallen if you want to discuss a rewrite (for say a v2.0) I'm happy to set up a call, just email me. But I do agree that the possibility of blowing up app code on unhandled rejection is a bad thing.

**Comment by billsaysthis** [comment]
Closing per above discussion.
