### ISSUE TITLE
client library shouldn't assume window

### ISSUE THREAD

**Issue by bryce-larson** [SumoLogic/js-sumo-logger#45]
We would like to use the client library for a isomorphic (server side rendered) React App, in addition use it within a React Native App.  Since this library assumes window and document are global, this will cause issues with the above two cases.

It would be nice if this library exported the function instead of making them available as part of global window object. 

instead of
```
  window.SLLogger = logger; // default global logger
  window.SumoLogger = SumoLogger; // To instantiate additional loggers
```
use:
```
export {SLLogger, SumoLogger}
```

The consumers could import the library as:
```
import { SLLogger, SumoLogger} from "sumo-logger";
```

**Comment by clementallen** [comment]
@bryce-larson is there any reason you are unable to use the cross-platform version? (sumoLogger.js);

I've mentioned before that I am keen for the separate client version  to be phased out as these days there is no need for two versions: https://github.com/SumoLogic/js-sumo-logger/issues/38#issuecomment-412548431

**Comment by bryce-larson** [comment]
@clementallen, I think the reason we choose the client lib, is we though the "sumoLogger.js" was just for node.js and the sumologic.logger.js was for the client.

> Included are a plain vanilla JavaScript version (sumologic.logger.js) for browser web apps and a Node.js module (sumoLogger.js).

Since we are building isomorphic, but only logging on the client side we thought we made the correct choice.  

Thank you, I'll try using the "sumoLogger.js" node module in the client.

**Comment by clementallen** [comment]
@bryce-larson a fair assumption, I'll look at getting the docs updated!  It was indeed once a node only library but has been updated to work cross platform which means there is no real need for two versions anymore but the other one is still kept around as it is still in use in older applications.

**Comment by billsaysthis** [comment]
The other issue is that the browser version (as noted in the README) is less secure since the endpoint is exposed to the world. @clementallen we should set up a call to discuss changes.

**Comment by billsaysthis** [comment]
Closing per above discussion.
