### ISSUE TITLE
SumoLogger not sending unhandled errors when `sendErrors` is set to `true`

### ISSUE THREAD

**Issue by jaknb** [SumoLogic/js-sumo-logger#47]
Example
```js
import SumoLogger from 'sumo-logger';

const opts = {
  endpoint: 'https://endpoint1.collection.eu.sumologic.com/receiver/v1/http/xxx',
  sendErrors: true,
  sourceName: 'xxx',
  sourceCategory: 'xxx',
  hostName: 'xxx',
};

const sumo = new SumoLogger(opts);
throw 'Dummy error!';
```

If I understand correctly the library should "catch" the unhandled error and send it as a log message.  Unfortunately, it's not happening and I don't know why. What am I missing?

**Comment by jaknb** [comment]
Now that I looked into `src` folder do I see correctly that starting with v2.0.0 `sendErrors` is no longer a feature?

**Comment by clementallen** [comment]
@jaknb `sendErrors` was supported in the web-only version of the sdk (`sumologic.logger.js`) but isn't currently supported in the newer cross-platform version.  However it could certainly be added as a feature as long as checks are made to ensure that it is only run on web-based platforms

**Comment by billsaysthis** [comment]
I reached out to our blog manager to find out the best way to get updated content out, will update this ticket when I hear back.

**Comment by billsaysthis** [comment]
I submitted an updated version of the blog post, seems reasonable to close this ticket.
