### ISSUE TITLE
Implement sumo logger in nextjs using react 

### ISSUE THREAD

**Issue by NirajCricket** [SumoLogic/js-sumo-logger#58]

**Comment by NirajCricket** [comment]
I want to implement sumo logger for logging in a application which is build on nextjs n top of nodejs

**Comment by clementallen** [comment]
@NirajCricket do you have a specific issue with this library?

**Comment by NirajCricket** [comment]
\

**Comment by NirajCricket** [comment]
Hi , are u from the support tema of sumo logic, can we have a call set up

**Comment by billsaysthis** [comment]
Hi Niraj, if you want to reach Sumo Logic Support you have to go through the regular channels.
