### ISSUE TITLE
Lodash security vulnerability

### ISSUE THREAD

**Issue by billsaysthis** [SumoLogic/js-sumo-logger#59]
Known low severity security vulnerability detected in lodash < 4.17.11 defined in package-lock.json.
--
package-lock.json update suggested: lodash ~> 4.17.11.

**Comment by clementallen** [comment]
@billsaysthis grunt is used for the demo (which I believe is very out of date already).  I think the two options would be to either:

1) Remove the demo all together from the repo, as the code examples in the README are probably all that's needed to start using the library in addition to the official Sumo documentation for HTTP endpoints.

2) Update the demo to stop using grunt (as it's not exactly the trending tooling currently) and use another tool (ideally a combination of different npm scripts).

My preference would be 1) but I'd be interested to see what you think :)

**Comment by billsaysthis** [comment]
Sorry, still thinking on this and also trying to close some Jiras ;)

**Comment by billsaysthis** [comment]
Closed with v2.1.0
