### ISSUE TITLE
Change default sending from seconds to seconds or number/size of messages

### ISSUE THREAD

**Issue by billsaysthis** [SumoLogic/js-sumo-logger#60]
There was some internal discussion recently about the optimal batching for HTTP endpoints and the recommendation is to send batches of 100KB to 1MB. This is a good balance of network traffic, app load, and use of receiver resources.

Specifically one of the engineers recommended we use both time and amount of logs, for example send everything if no sends on last <N> seconds or send when there are 100 logs or 100KB of logs. Sending resets both counts.

@clementallen  Looking for feedback on this change.

**Comment by clementallen** [comment]
@billsaysthis sorry I did see your email the other week but then I went on vacation and when I got back normal work kept me busy :)

I've had a little think and have a few questions:

1) I'm presuming we can still keep the default to be sending each log message as it's received?

2) How would we calculate the size of the pending logs to be sent? Not a common task in JS and does that size limit refer to memory allocation or network request size?

3) 100kb seems quite high for a minimum to me.  With my current use of Sumo I am sending a fairly large JSON payload in each log file (roughly 40-50 attributes) and this only consumes < 0.5kb of bandwidth.  With a 100kb minimum send size we would have to wait for a pending stack of more than 200 log files which is quite a lot.  I would suggest setting a lower minimum of around 10kb.

Interested to see your views! :)

**Comment by billsaysthis** [comment]
1. Yes, we can keep that as an option.
2. The number of characters in the message is sufficiently close to use
3. The 100K comes from the Collectors team, this is their best practices recommendation. BUT, this would be size or time, whichever comes first. So say after five seconds since last send you only have 10 logs (5K total), it would still send.

**Comment by clementallen** [comment]
Okay that all sounds good to me.  Would the size also be configurable along side the existing time config option?

**Comment by billsaysthis** [comment]
Sure, why not?

**Comment by clementallen** [comment]
Excellent, no further questions!  Sounds like a good addition to the library 👍

**Comment by billsaysthis** [comment]
Implemented in https://github.com/SumoLogic/js-sumo-logger/pull/64
