### ISSUE TITLE
Logs are missed, if they were logged during axios request performing

### ISSUE THREAD

**Issue by zanctor** [SumoLogic/js-sumo-logger#66]
Hi! 

I faced the issue when some logs were missed using interval-based logs sending. So I added console logs with the `pendingLogs` length before the request and within `then` section. Sometimes the log length before `this.pendingLogs = []` is bigger than before request.

Could you please help with it?
Thanks!

**Comment by billsaysthis** [comment]
Thanks for the bug report, on it.

**Comment by billsaysthis** [comment]
Please pull the new release and let me know if it fixes your issue.

**Comment by zanctor** [comment]
@billsaysthis, it is working, thanks!
