### ISSUE TITLE
Single log messages sent forever when interval set and returnPromise in default state

### ISSUE THREAD

**Issue by SLKnutson** [SumoLogic/js-sumo-logger#70]
Because the return promise code path through sendLogs does not remove the logs from the pending logs, if you configure to use batching (interval > 0) and do not explicitly set returnPromise to false (it defaults to true), then single logs will get caught and continually sent at the interval frequency.
Ideally, the log should only be send once regardless of what returnPromise is set to

**Comment by billsaysthis** [comment]
@clementallen I'm looking at sumoLogger.js lines 132-139 and thinking we need to add `.then/.catch` blocks to the `.post`. Seem correct to you?

**Comment by clementallen** [comment]
@billsaysthis agree, and clear the pending logs on success of the axios call

**Comment by billsaysthis** [comment]
https://github.com/SumoLogic/js-sumo-logger/pull/72

**Comment by billsaysthis** [comment]
@SLKnutson The PR has been merged, can you test that it fixes your issue and if so please close this issue. Thanks!

**Comment by SLKnutson** [comment]
@billsaysthis Looks good in my app. Thanks!

**Comment by billsaysthis** [comment]
Closing per @SLKnutson comment
