### ISSUE TITLE
Logging throws exception and goes into infinite send loop when in buffered send mode

### ISSUE THREAD

**Issue by JK0N** [SumoLogic/js-sumo-logger#81]
When it sends the data, and formats the response in "marshalHttpResponse" -function, response.statusText is undefined and response.res is undefined so it throws exception.

- If it's running in buffered send mode (interval option !== 0), the exception causes it to never remove sent element from buffer and it will send it again after interval.

`
statusText: response.statusText || response.res.statusMessage,
`
https://github.com/SumoLogic/js-sumo-logger/blob/master/src/sumoLogger.js#L28

Not sure why the response is missing, has something been changed on the collector endpoint?

**Comment by billsaysthis** [comment]
Hi @JK0N thanks for the issue. Can you pull new branch `add-default-statusText` and see if this fixes the problem? If it does I'll merge and publish.

**Comment by JK0N** [comment]
Hello! Thanks for quick reply!

`statusText: response.statusText || response.res.statusMessage || '',
`
I didn't try it out but it will still throw exception as response.res is undefined and it is trying to evaluate statusMessage property of undefined

**Comment by billsaysthis** [comment]
I updated the branch to also handle `response.res` being undefined.

**Comment by JK0N** [comment]
Great, this works!

**Comment by billsaysthis** [comment]
https://github.com/SumoLogic/js-sumo-logger/pull/82 published as v2.5.2, thanks for the bug report and testing support!
