### ISSUE TITLE
Error when determining timezone

### ISSUE THREAD

**Issue by skinnybeans** [SumoLogic/js-sumo-logger#85]
In the `formateDate` function there's an error when determining the timezone.

It uses the following method:

`var timezone = JSON.stringify(date).split('GMT')[1] || '+000';`

However, the output of `JSON.stringify(date)` is an ISO formatted time:

`2019-07-12T04:21:17.821Z`

This means the timezone is always being set to `+000` as there is no `GMT` substring found.

In this case, the timezone should be set to +1000.

**Comment by billsaysthis** [comment]
I see your point, but not getting the `+1000` part.

**Comment by skinnybeans** [comment]
Oh sorry that's my timezone, I'm in GMT +10

**Comment by billsaysthis** [comment]
@skinnybeans Can you review https://github.com/SumoLogic/js-sumo-logger/pull/86 to see if it fixes your issue? Github is not letting me specify you as a reviewer or assignee.

**Comment by billsaysthis** [comment]
Resolved by https://github.com/SumoLogic/js-sumo-logger/pull/86, published as v2.5.4.
