### ISSUE TITLE
Request for httpOnly / Secure Cookie

### ISSUE THREAD

**Issue by roger-intive-fdv** [SumoLogic/js-sumo-logger#90]
When we connect using this API, the browser session for our application sets a cookie named sumologic.logger.session that is not secure not httpOnly.

We are under a strict security requirement that demands having all cookies with those conditions.

Is there a possible solution to this issue? We've contacted support and they suggested us to raise a ticket here.

Thanks!

**Comment by billsaysthis** [comment]
@clementallen @yelvert what do you think of this request? Should it be an option (on or off by default) or always sent?

**Comment by clementallen** [comment]
@roger-intive-fdv @billsaysthis that cookie is only used in the deprecated client-only version of this lib.  We recommend using the latest version installable from npm if possible which does not set any cookies

**Comment by billsaysthis** [comment]
Per the above, please update to the new version as we deprecated the script you're using quite a while back and will probably EOL it early in 2020.
