### ISSUE TITLE
returnPromise property not declared in SumoLoggerOptions

### ISSUE THREAD

**Issue by sauravksingh** [SumoLogic/js-sumo-logger#92]
This missing property in the typescript declarations forces one to use the callback options.

**Comment by billsaysthis** [comment]
@sauravksingh  Sorry for the delay in responding, got caught up in some other work. Not clear on which typescript declarations you're referring to, since there are none in this repo. Can you clarify?

**Comment by billsaysthis** [comment]
Closing for lack of response
